WXR\CategoryBundle\Entity\BaseCategory:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        position:
            type: integer
            gedmo:
                - sortablePosition
        slug:
            type: string
            length: 255
            gedmo:
                slug: { fields: [ name ] }
        description:
            type: text
            nullable: true
